### ISSUE TITLE
error launching language server

### ISSUE THREAD

**Issue by masterkain** [ruby-syntax-tree/vscode-syntax-tree#113]
I'm not sure since which version, but anyway I have the syntax_tree-3.6.1 gem installed and the extension keeps complaining

```
Starting language server: 0 lsp --plugins=plugin/single_quotes --print-width=200
[Error - 1:37:02 PM] Syntax Tree client: couldn't create connection to server.
Launching server using command 0 failed. Error: spawn 0 ENOENT
```

```
% which stree
/Users/kain/.rvm/gems/ruby-3.0.0/bin/stree

echo $PATH
/Users/kain/.rvm/gems/ruby-3.0.0/bin:/Users/kain/.rvm/gems/ruby-3.0.0@global/bin:/Users/kain/.rvm/rubies/ruby-3.0.0/bin:etcetcetc
```

**Comment by kddnewton** [comment]
Oh gosh, I'm really sorry about that. That's some new code that just went out. I just fixed it and released v0.5.1 which contains the fix. Let me know if you have any further trouble. Thanks for reporting.
