### ISSUE TITLE
Extension is adding "decorations" around binary ops

### ISSUE THREAD

**Issue by chasestubblefield** [ruby-syntax-tree/vscode-syntax-tree#199]
I'm not sure what to call these other than "decorations", but I'm now seeing this around some uses of `||` and `-`:
![Screenshot 2022-12-23 at 1 08 13 AM](https://user-images.githubusercontent.com/606164/209335815-67846994-6648-4ec4-b909-d0c0fa460963.png)
They disappear when I disable this extension. I call them "decorations" because they're not in the file, only part of the editor. They only started appearing since the last update. I'd like to at least have some setting to disable them.

**Comment by kddnewton** [comment]
You can turn this off in your VSCode settings by turning off "inlay hints"
