### ISSUE TITLE
Update version in VSCode marketplace?

### ISSUE THREAD

**Issue by xfalcox** [ruby-syntax-tree/vscode-syntax-tree#24]
The current one was last updated in April and it doesn't work for me.

Compiling manually from `main` branch (after fixing a dependency version) and installing the resulting VSIX manually makes it work.

Can we get the updated one in the marketplace?

**Comment by kddnewton** [comment]
Hello! Yes I'll release one today.

**Comment by kddnewton** [comment]
Updated! 0.2.3 in the marketplace.
