### ISSUE TITLE
Need a way to control the language server configuration

### ISSUE THREAD

**Issue by xeger** [ruby-syntax-tree/vscode-syntax-tree#3]
My goal is to choose which syntax_tree plugins the LSP should use when formatting my code. I'm fed up with `rebornix.ruby` and would much rather use `vscode-syntax-tree` plus `syntax_tree` -- but I need to be able to configure the thing to match my coding standard.

[This proposal](https://github.com/ruby-syntax-tree/vscode-syntax-tree/compare/main...xeger:config) adds some straightforward configuration, but it turns out that `stree lsp` doesn't bother to parse options, hence my [proposed fix in the syntax_tree repo](https://github.com/ruby-syntax-tree/syntax_tree/pull/99), which this proposal depends on.

Thoughts on this whole scheme?

**Comment by kddnewton** [comment]
I believe since that other PR you mentioned is merged now, this can be closed. Let me know if you meant for anything else here.

**Comment by xeger** [comment]
Not quite, as I haven't completed the proposal for adding options to the extension - got waylaid by the restart and shutdown issues. I'll turn my working proposal into a PR once I've fixed the re-reg thing and we can talk it over with a concrete example in front of you.
