### ISSUE TITLE
VSCode does not pick up `stree`

### ISSUE THREAD

**Issue by danbee** [ruby-syntax-tree/vscode-syntax-tree#341]
Hi, I'm trying to set up our project to use `syntax_tree` for Ruby code formatting, and I'm having some trouble getting the VSCode extension to consistently pick up the `stree` executable. If I launch VSCode using the CLI tool (eg. `code .`) or using the `.code-workspace` file in our project it all works correctly.

However, if I just launch VSCode directly from the OS (macOS Ventura in this case), I get the following error messages and code formatting does not work.

<img width="471" alt="image" src="https://github.com/ruby-syntax-tree/syntax_tree/assets/165531/95932d4a-84a4-4c48-a8e6-88ba0be8e0b7">

```
Starting language server: stree lsp
[Error - 3:09:05 PM] Syntax Tree client: couldn't create connection to server.
Launching server using command stree failed. Error: spawn stree ENOENT
```

`syntax_tree` is installed in the bundle for the application and also globally. I use `asdf` for managing Ruby versions on my machine.

If I click on the "Install Gem" button I get an error about permissions:

```
Error installing gem: Error: Command failed: gem install syntax_tree
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```

This suggests that it's trying to install the gem for the system Ruby version rather than the version of Ruby selected by `asdf`.

**Comment by Frexuz** [comment]
Same here

**Comment by kddnewton** [comment]
This is a little outside my control unfortunately, so it's mostly dependent on how you set up your system. If it's within a project, clearly it's picking it up correctly. If it's _not_ within a project, then it's going to be dependent on how `gem` resolves on your system. If you're using something like `chruby`, `rvm`, or `rbenv`, then they all have options to set how the global `gem` command resolves. I'm sorry I don't know `asdf` very well, but I'm sure there's a way to make it resolve your correct Ruby versions on login. I would suggest starting there.

**Comment by pmusaraj** [comment]
For any passers-by, I found a solution for this. Set up the Ruby LSP extension for VS Code, and then configure it to use the Ruby version manager of your choice. Once that is done, you will still see the same warnings as in the OP, but the Restart button works, it will load `stree` using the correct Ruby version.
