### ISSUE TITLE
Bundle the extension with esbuild

### ISSUE THREAD

**Issue by kddnewton** [ruby-syntax-tree/vscode-syntax-tree#35]
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by kddnewton** [comment]
@xeger wanna take a shot at this? The docs look pretty clear on this, shouldn't be too bad. Seems like something worth doing (I get a warning every time I publish it that I should be doing this).

**Comment by xeger** [comment]
It wasn't a slam dunk, but I made a start at it for you. See the PR for my concerns.

I'm mildly surprised that the official Microsoft documentation has people bundling tests with tsc, and distributables with esbuild -- they must really trust both tools!
