### ISSUE TITLE
Bracket decorators aren't properly sized

### ISSUE THREAD

**Issue by devonpmack** [ruby-syntax-tree/vscode-syntax-tree#65]
The brackets are not sized correctly for the font. 

<img width="155" alt="image" src="https://user-images.githubusercontent.com/21130966/185658415-e2113c00-b46c-491f-9098-f58cbe276014.png">

**Comment by kddnewton** [comment]
Yeah they're intentionally small. Though in that font they look like they're a little below the line which is weird. But they're supposed to be small to not get misinterpreted as real parentheses.

**Comment by devonpmack** [comment]
@kddnewton Should we center them on the line?

**Comment by kddnewton** [comment]
You can control that in your editor in the settings - you can set a font, size, padding, all kinds of stuff. I think we just want to provide the content in this plugin.

**Comment by devonpmack** [comment]
Oddly the inlay font size doesn't seem to work on them, not sure why :/
